TARGET = 0a
CC = g++


$(TARGET) : main.o module1.o module2.o module3.o
	$(CC) main.o module1.o module2.o module3.o -o $(TARGET)

main.o : main.cpp
	$(CC) -c main.cpp -o main.o

module1.o : module1.cpp
	$(CC) -c module1.cpp -o module1.o

module2.o : module2.cpp
	$(CC) -c module2.cpp -o module2.o


module3.o : module3.cpp
	$(CC) -c module3.cpp -o module3.o

clean:
	del $(TARGET) *.o